### ISSUE TITLE
Cannot login when running from docker-compose.yml file due to CORS errors

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager#15]
I followed the [guide](https://github.com/kbss-cvut/record-manager/blob/main/doc/setup.md#docker-compose-deployment), but I am not able to log into the record manager.

I get the following error related to CORS:
```
Access to XMLHttpRequest at 'http://localhost:8080/record-manager-server/rest/users/current' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

See the screenshot:
![image](https://github.com/kbss-cvut/record-manager/assets/3962237/8b257aa0-72c6-492f-abdc-b253a0d1ec2c)

This is CORS setting in record-manager-server service:
![image](https://github.com/kbss-cvut/record-manager/assets/3962237/40af7236-2213-4189-8a50-fb8756b5a217)

I believe that the the wird setting has nothing to do with it -- i described it [here](https://github.com/kbss-cvut/record-manager/issues/13) and [created PR (still WIP)](https://github.com/kbss-cvut/record-manager/pull/14).

**Comment by ledsoft** [comment]
@blcham Works fine for me. Could you check with the preflight request returns 404?

**Comment by ledsoft** [comment]
Was caused by a configuration issue.

**Comment by blcham** [comment]
Fixed by https://github.com/kbss-cvut/record-manager/commit/a98a4f27078c2b30ec25cd918c77c9917f92d451
