### ISSUE TITLE
Record should have states for actions complete/reject/accept

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager#29]
We have roles:
OA - operator admin
SA - supplier admin

We have following states of record:
- 1) open record (manually by "save record" or automatic when record is imported)
- 2) valid record (automatic)
- 3) completed record (either manually or automatically if valid)
- 4) accepted record (manually)
- 5) rejected record (manually)

-----

In AVA we have:
- open
- closed
- published
- unpublished
- processed
- unprocessed
- rejected
- approved
- grounded

![Image](https://github.com/kbss-cvut/record-manager/assets/3962237/c03fc838-0aab-4d55-835c-9ac739c573f3)

and we map:
-  3) to button "Complete" (closed in AVA)  to do "valid record-> completed record" 
-  4) to button "Approve" to do "accepted record"
-  5) to button "Reject" to do "rejected record"

(All buttons from [Have posibility in RM to complete set of records](https://github.com/kbss-cvut/record-manager-ui/issues/18) are covered)

A/C:
- design the model in RM and map it to AVA model above
- implement it in RM backend service related to records

**Comment by blcham** [comment]
TODO:
- we need validated failure record

**Comment by blcham** [comment]
Here is the mapping:
![Image](https://github.com/kbss-cvut/record-manager/assets/3962237/e7e30f0e-1131-4596-8e91-71731ce9fd86)


Here is mapping to icons:
![Image](https://github.com/kbss-cvut/record-manager/assets/3962237/704eb894-9844-48dc-85fd-c9bfd8370de7)

**Comment by LaChope** [comment]
@blcham Just to make sure, there should not be any "Accept" button anymore, only reject right?

**Comment by blcham** [comment]
@kostobog still need to refactor labels in ontology "record state" --> "record phase" + there is missing enum "rejected"

**Comment by kostobog** [comment]
@blcham labels fixed in kbss-cvut/record-manager#36.
