### ISSUE TITLE
Execution of docker image is not working on arm64 processors (Mac M1)

### ISSUE THREAD

**Issue by shellyear** [kbss-cvut/record-manager#47]
The error is:
`qemu: uncaught target signal 11 (Segmentation fault) - core dumped`
![image](https://github.com/kbss-cvut/record-manager/assets/50382323/eb143e82-80c4-4412-acc3-be4decfefb52)

It was described in:
https://github.com/docker/for-mac/issues/5123#issuecomment-784992589

**Comment by blcham** [comment]
Also relates to:
https://github.com/easimon/bug-reproducers/tree/eclipse-temurin-arm32?tab=readme-ov-file#readme

**Comment by blcham** [comment]
This error occurred after the update of Docker Desktop:
https://github.com/docker/for-mac/issues/7172
