### ISSUE TITLE
Users should be persisted in separate context

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager#74]
Same way as it is done in fta-fmea tool.

**Comment by blcham** [comment]
Blocked by https://github.com/kbss-cvut/record-manager-ui/pull/208

**Comment by palagdan** [comment]
@blcham,

It’s a bit confusing. I checked the implementation in FTA-FMEA and noticed that some users (test1 and test2) are in a separate context:
[http://context-with-users](http://localhost:1235/services/db-server/resource?uri=http%3A%2F%2Fcontext-with-users&role=context)
![Image](https://github.com/user-attachments/assets/81e027ce-1de5-476a-b657-6116933e5fc8)



In the internal authorization, I created two users, and they are stored without a context:
![Image](https://github.com/user-attachments/assets/495c4017-3ef8-4705-be6f-e7722acba7fc)

I’m not sure which option I should implement in RM:

Create a new context for each user.
Use a common context, like [http://context-with-users](http://localhost:1235/services/db-server/resource?uri=http%3A%2F%2Fcontext-with-users&role=context).

**Comment by blcham** [comment]
I updated A/C to include migration script
